//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpleadoConsulta.ConsultaEmpleado {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsultaEmpleado.IServicioConsulta")]
    public interface IServicioConsulta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/Todos", ReplyAction="http://tempuri.org/IServicioConsulta/TodosResponse")]
        AplicacionDeServicios.Response.ResponseEmpleado Todos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/Todos", ReplyAction="http://tempuri.org/IServicioConsulta/TodosResponse")]
        System.Threading.Tasks.Task<AplicacionDeServicios.Response.ResponseEmpleado> TodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/Buscar", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarResponse")]
        AplicacionDeServicios.Response.ResponseEmpleado Buscar(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/Buscar", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarResponse")]
        System.Threading.Tasks.Task<AplicacionDeServicios.Response.ResponseEmpleado> BuscarAsync(string palabra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioConsultaChannel : EmpleadoConsulta.ConsultaEmpleado.IServicioConsulta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConsultaClient : System.ServiceModel.ClientBase<EmpleadoConsulta.ConsultaEmpleado.IServicioConsulta>, EmpleadoConsulta.ConsultaEmpleado.IServicioConsulta {
        
        public ServicioConsultaClient() {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AplicacionDeServicios.Response.ResponseEmpleado Todos() {
            return base.Channel.Todos();
        }
        
        public System.Threading.Tasks.Task<AplicacionDeServicios.Response.ResponseEmpleado> TodosAsync() {
            return base.Channel.TodosAsync();
        }
        
        public AplicacionDeServicios.Response.ResponseEmpleado Buscar(string palabra) {
            return base.Channel.Buscar(palabra);
        }
        
        public System.Threading.Tasks.Task<AplicacionDeServicios.Response.ResponseEmpleado> BuscarAsync(string palabra) {
            return base.Channel.BuscarAsync(palabra);
        }
    }
}
