//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpleadoConsulta.ServicioDeConsulta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioDeConsulta.IServicioConsulta")]
    public interface IServicioConsulta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorId", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorIdResponse")]
        AplicacionDeServicios.Empleado BuscarPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorId", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorIdResponse")]
        System.Threading.Tasks.Task<AplicacionDeServicios.Empleado> BuscarPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorNombre", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorNombreResponse")]
        AplicacionDeServicios.Empleado[] BuscarPorNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorNombre", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorNombreResponse")]
        System.Threading.Tasks.Task<AplicacionDeServicios.Empleado[]> BuscarPorNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorLegajo", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorLegajoResponse")]
        AplicacionDeServicios.Empleado[] BuscarPorLegajo(string legajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorLegajo", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorLegajoResponse")]
        System.Threading.Tasks.Task<AplicacionDeServicios.Empleado[]> BuscarPorLegajoAsync(string legajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorDNI", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorDNIResponse")]
        AplicacionDeServicios.Empleado[] BuscarPorDNI(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorDNI", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorDNIResponse")]
        System.Threading.Tasks.Task<AplicacionDeServicios.Empleado[]> BuscarPorDNIAsync(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorApellido", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorApellidoResponse")]
        AplicacionDeServicios.Empleado[] BuscarPorApellido(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/BuscarPorApellido", ReplyAction="http://tempuri.org/IServicioConsulta/BuscarPorApellidoResponse")]
        System.Threading.Tasks.Task<AplicacionDeServicios.Empleado[]> BuscarPorApellidoAsync(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/Todos", ReplyAction="http://tempuri.org/IServicioConsulta/TodosResponse")]
        AplicacionDeServicios.Empleado[] Todos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/Todos", ReplyAction="http://tempuri.org/IServicioConsulta/TodosResponse")]
        System.Threading.Tasks.Task<AplicacionDeServicios.Empleado[]> TodosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioConsultaChannel : EmpleadoConsulta.ServicioDeConsulta.IServicioConsulta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConsultaClient : System.ServiceModel.ClientBase<EmpleadoConsulta.ServicioDeConsulta.IServicioConsulta>, EmpleadoConsulta.ServicioDeConsulta.IServicioConsulta {
        
        public ServicioConsultaClient() {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AplicacionDeServicios.Empleado BuscarPorId(int id) {
            return base.Channel.BuscarPorId(id);
        }
        
        public System.Threading.Tasks.Task<AplicacionDeServicios.Empleado> BuscarPorIdAsync(int id) {
            return base.Channel.BuscarPorIdAsync(id);
        }
        
        public AplicacionDeServicios.Empleado[] BuscarPorNombre(string nombre) {
            return base.Channel.BuscarPorNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<AplicacionDeServicios.Empleado[]> BuscarPorNombreAsync(string nombre) {
            return base.Channel.BuscarPorNombreAsync(nombre);
        }
        
        public AplicacionDeServicios.Empleado[] BuscarPorLegajo(string legajo) {
            return base.Channel.BuscarPorLegajo(legajo);
        }
        
        public System.Threading.Tasks.Task<AplicacionDeServicios.Empleado[]> BuscarPorLegajoAsync(string legajo) {
            return base.Channel.BuscarPorLegajoAsync(legajo);
        }
        
        public AplicacionDeServicios.Empleado[] BuscarPorDNI(string DNI) {
            return base.Channel.BuscarPorDNI(DNI);
        }
        
        public System.Threading.Tasks.Task<AplicacionDeServicios.Empleado[]> BuscarPorDNIAsync(string DNI) {
            return base.Channel.BuscarPorDNIAsync(DNI);
        }
        
        public AplicacionDeServicios.Empleado[] BuscarPorApellido(string apellido) {
            return base.Channel.BuscarPorApellido(apellido);
        }
        
        public System.Threading.Tasks.Task<AplicacionDeServicios.Empleado[]> BuscarPorApellidoAsync(string apellido) {
            return base.Channel.BuscarPorApellidoAsync(apellido);
        }
        
        public AplicacionDeServicios.Empleado[] Todos() {
            return base.Channel.Todos();
        }
        
        public System.Threading.Tasks.Task<AplicacionDeServicios.Empleado[]> TodosAsync() {
            return base.Channel.TodosAsync();
        }
    }
}
